model: 'CT'
network: 'ro_34'
task: 'snake'
collator: 'medical'
resume: true
gpus: (0,)
shot: 1

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 64
    dataset: 'SABSTrain'
    num_workers: 0
    epoch: 151
test:
    dataset: 'SABSVal'
    batch_size: 1

heads: {'ct_hm': 20, 'wh': 2}
segm_or_bbox: 'segm'
