model: 'sbd'
network: 'ro_34'
task: 'snake'
resume: true
gpus: (0, 1, 2, 3)

train:
    optim: 'adam'
    lr: 1.25e-5
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 4
    dataset: 'SbdTrain'
    num_workers: 0
    epoch: 6
test:
    dataset: 'SbdMini'
    batch_size: 1

heads: {'ct_hm': 20, 'wh': 2}
segm_or_bbox: 'segm'
